version: '3'

services:
  web:
    build: .
    command: gunicorn management_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/  # 경로를 수정하세요
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:  #
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: management_dev
      POSTGRES_USER: management_db_user
      POSTGRES_PASSWORD: management_db_password

volumes:
  postgres_data:
