# Generated by Django 4.2.5 on 2023-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0003_rename_contents_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="teamangel/files/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="teamangel/images/%Y/%m/%d"),
        ),
    ]
