# Generated by Django 4.2.5 on 2023-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0005_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
