# Generated by Django 4.2.5 on 2023-09-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0006_post_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="views",
        ),
    ]
