# Generated by Django 4.2.5 on 2023-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0010_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
