# Generated by Django 4.2.5 on 2023-09-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0012_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="teamangel/images/%Y/%m/%d"),
        ),
    ]
