# Generated by Django 4.2.5 on 2023-09-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teamangel", "0013_alter_postimage_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
